--------------------------------------------------------
--  文件已创建 - 星期三-六月-16-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for View MVIEW_EVALUATIONS
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "SYSTEM"."MVIEW_EVALUATIONS" ("RUNID", "MVIEW_OWNER", "MVIEW_NAME", "RANK", "STORAGE_IN_BYTES", "FREQUENCY", "CUMULATIVE_BENEFIT", "BENEFIT_TO_COST_RATIO") AS 
  select
  t1.runid# as runid,
  summary_owner AS mview_owner,
  summary_name AS mview_name,
  rank# as rank,
  storage_in_bytes,
  frequency,
  cumulative_benefit,
  benefit_to_cost_ratio
from SYSTEM.MVIEW$_ADV_OUTPUT t1, SYSTEM.MVIEW$_ADV_LOG t2, ALL_USERS u
where
  t1.runid# = t2.runid# and
  u.username = t2.uname and
  u.user_id = userenv('SCHEMAID') and
  t1.output_type = 1
order by t1.rank#;

   COMMENT ON TABLE "SYSTEM"."MVIEW_EVALUATIONS"  IS 'This view gives DBA access to summary evaluation output';
--------------------------------------------------------
--  DDL for View MVIEW_EXCEPTIONS
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "SYSTEM"."MVIEW_EXCEPTIONS" ("RUNID", "OWNER", "TABLE_NAME", "DIMENSION_NAME", "RELATIONSHIP", "BAD_ROWID") AS 
  select
  t1.runid# as runid,
  owner,
  table_name,
  dimension_name,
  relationship,
  bad_rowid
from SYSTEM.MVIEW$_ADV_EXCEPTIONS t1, SYSTEM.MVIEW$_ADV_LOG t2, ALL_USERS u
where
  t1.runid# = t2.runid# and
  u.username = t2.uname and
  u.user_id = userenv('SCHEMAID');

   COMMENT ON TABLE "SYSTEM"."MVIEW_EXCEPTIONS"  IS 'This view gives DBA access to dimension validation results';
--------------------------------------------------------
--  DDL for View MVIEW_FILTER
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "SYSTEM"."MVIEW_FILTER" ("FILTERID", "SUBFILTERNUM", "SUBFILTERTYPE", "STR_VALUE", "NUM_VALUE1", "NUM_VALUE2", "DATE_VALUE1", "DATE_VALUE2") AS 
  select
      a.filterid# as filterid,
      a.subfilternum# as subfilternum,
      decode(a.subfiltertype,1,'APPLICATION',2,'CARDINALITY',3,'LASTUSE',
                             4,'FREQUENCY',5,'USER',6,'PRIORITY',7,'BASETABLE',
                             8,'RESPONSETIME',9,'COLLECTIONID',10,'TRACENAME',
                             11,'SCHEMA','UNKNOWN') AS subfiltertype,
      a.str_value,
      to_number(decode(a.num_value1,-999,NULL,a.num_value1)) AS num_value1,
      to_number(decode(a.num_value2,-999,NULL,a.num_value2)) AS num_value2,
      a.date_value1,
      a.date_value2
   from system.mview$_adv_filter a, system.mview$_adv_log b, ALL_USERS u
   WHERE a.filterid# = b.runid#
   AND b.uname = u.username
   AND u.user_id = userenv('SCHEMAID');

   COMMENT ON TABLE "SYSTEM"."MVIEW_FILTER"  IS 'Workload filter records';
--------------------------------------------------------
--  DDL for View MVIEW_FILTERINSTANCE
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "SYSTEM"."MVIEW_FILTERINSTANCE" ("RUNID", "FILTERID", "SUBFILTERNUM", "SUBFILTERTYPE", "STR_VALUE", "NUM_VALUE1", "NUM_VALUE2", "DATE_VALUE1", "DATE_VALUE2") AS 
  select
      a.runid# as runid,
      a.filterid# as filterid,
      a.subfilternum# as subfilternum,
      decode(a.subfiltertype,1,'APPLICATION',2,'CARDINALITY',3,'LASTUSE',
                             4,'FREQUENCY',5,'USER',6,'PRIORITY',7,'BASETABLE',
                             8,'RESPONSETIME',9,'COLLECTIONID',10,'TRACENAME',
                             11,'SCHEMA','UNKNOWN') AS subfiltertype,
      a.str_value,
      to_number(decode(a.num_value1,-999,NULL,a.num_value1)) AS num_value1,
      to_number(decode(a.num_value2,-999,NULL,a.num_value2)) AS num_value2,
      a.date_value1,
      a.date_value2
   from system.mview$_adv_filterinstance a;

   COMMENT ON TABLE "SYSTEM"."MVIEW_FILTERINSTANCE"  IS 'Workload filter instance records';
--------------------------------------------------------
--  DDL for View MVIEW_LOG
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "SYSTEM"."MVIEW_LOG" ("ID", "FILTERID", "RUN_BEGIN", "RUN_END", "TYPE", "STATUS", "MESSAGE", "COMPLETED", "TOTAL", "ERROR_CODE") AS 
  select
      m.runid# as id,
      m.filterid# as filterid,
      m.run_begin,
      m.run_end,
      decode(m.run_type,1,'EVALUATE',2,'EVALUATE_W',3,'RECOMMEND',
                      4,'RECOMMEND_W',5,'VALIDATE',6,'WORKLOAD',
                      7,'FILTER','UNKNOWN') AS type,
      decode(m.status,0,'UNUSED',1,'CANCELLED',2,'IN_PROGRESS',3,'COMPLETED',
                    4,'ERROR','UNKNOWN') AS status,
      m.message,
      m.completed,
      m.total,
      m.error_code
   from system.mview$_adv_log m, all_users u
   where m.uname = u.username
   and   u.user_id = userenv('SCHEMAID');

   COMMENT ON TABLE "SYSTEM"."MVIEW_LOG"  IS 'Advisor session log';
--------------------------------------------------------
--  DDL for View MVIEW_RECOMMENDATIONS
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "SYSTEM"."MVIEW_RECOMMENDATIONS" ("RUNID", "ALL_TABLES", "FACT_TABLES", "GROUPING_LEVELS", "QUERY_TEXT", "RECOMMENDATION_NUMBER", "RECOMMENDED_ACTION", "MVIEW_OWNER", "MVIEW_NAME", "STORAGE_IN_BYTES", "PCT_PERFORMANCE_GAIN", "BENEFIT_TO_COST_RATIO") AS 
  select
  t1.runid# as runid,
  t1.from_clause as all_tables,
  fact_tables,
  grouping_levels,
  query_text,
  rank# as recommendation_number,
  action_type as recommended_action,
  summary_owner as mview_owner,
  summary_name as mview_name,
  storage_in_bytes,
  pct_performance_gain,
  benefit_to_cost_ratio
from SYSTEM.MVIEW$_ADV_OUTPUT t1, SYSTEM.MVIEW$_ADV_LOG t2, ALL_USERS u
where
  t1.runid# = t2.runid# and
  u.username = t2.uname and
  u.user_id = userenv('SCHEMAID') and
  t1.output_type = 0
order by t1.rank#;

   COMMENT ON TABLE "SYSTEM"."MVIEW_RECOMMENDATIONS"  IS 'This view gives DBA access to summary recommendations';
--------------------------------------------------------
--  DDL for View MVIEW_WORKLOAD
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "SYSTEM"."MVIEW_WORKLOAD" ("WORKLOADID", "IMPORT_TIME", "QUERYID", "APPLICATION", "CARDINALITY", "RESULTSIZE", "LASTUSE", "FREQUENCY", "OWNER", "PRIORITY", "QUERY", "RESPONSETIME") AS 
  select
  a.collectionid# as workloadid,
  a.collecttime as import_time,
  a.queryid# as queryid,
  a.application,
  a.cardinality,
  a.resultsize,
  a.qdate as lastuse,
  a.frequency,
  a.uname as owner,
  a.priority,
  a.sql_text as query,
  a.exec_time as responsetime
from SYSTEM.MVIEW$_ADV_WORKLOAD A, SYSTEM.MVIEW$_ADV_LOG B, ALL_USERS D
WHERE a.collectionid# = b.runid#
AND b.uname = d.username
AND d.user_id = userenv('SCHEMAID');

   COMMENT ON TABLE "SYSTEM"."MVIEW_WORKLOAD"  IS 'This view gives DBA access to shared workload';
--------------------------------------------------------
--  DDL for View PRODUCT_PRIVS
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "SYSTEM"."PRODUCT_PRIVS" ("PRODUCT", "USERID", "ATTRIBUTE", "SCOPE", "NUMERIC_VALUE", "CHAR_VALUE", "DATE_VALUE", "LONG_VALUE") AS 
  SELECT PRODUCT, USERID, ATTRIBUTE, SCOPE,
         NUMERIC_VALUE, CHAR_VALUE, DATE_VALUE, LONG_VALUE
  FROM SQLPLUS_PRODUCT_PROFILE
  WHERE USERID = 'PUBLIC' OR USER LIKE USERID;
--------------------------------------------------------
--  DDL for View SCHEDULER_JOB_ARGS
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "SYSTEM"."SCHEDULER_JOB_ARGS" ("OWNER", "JOB_NAME", "ARGUMENT_NAME", "ARGUMENT_POSITION", "ARGUMENT_TYPE", "VALUE", "ANYDATA_VALUE", "OUT_ARGUMENT") AS 
  SELECT "OWNER","JOB_NAME","ARGUMENT_NAME","ARGUMENT_POSITION","ARGUMENT_TYPE","VALUE","ANYDATA_VALUE","OUT_ARGUMENT" FROM sys.all_scheduler_job_args;
--------------------------------------------------------
--  DDL for View SCHEDULER_PROGRAM_ARGS
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "SYSTEM"."SCHEDULER_PROGRAM_ARGS" ("OWNER", "PROGRAM_NAME", "ARGUMENT_NAME", "ARGUMENT_POSITION", "ARGUMENT_TYPE", "METADATA_ATTRIBUTE", "DEFAULT_VALUE", "DEFAULT_ANYDATA_VALUE", "OUT_ARGUMENT") AS 
  SELECT "OWNER","PROGRAM_NAME","ARGUMENT_NAME","ARGUMENT_POSITION","ARGUMENT_TYPE","METADATA_ATTRIBUTE","DEFAULT_VALUE","DEFAULT_ANYDATA_VALUE","OUT_ARGUMENT" FROM sys.all_scheduler_program_args;
--------------------------------------------------------
--  DDL for Type LOGMNR$COL_GG_REC
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TYPE "SYSTEM"."LOGMNR$COL_GG_REC" as object
(
LOGMNR_UID NUMBER,
OBJ# NUMBER,
MD_COL_NAME VARCHAR2(384),
MD_COL_NUM NUMBER,                 /* col# */
MD_COL_SEGCOL NUMBER,              /* segcol# */
MD_COL_TYPE NUMBER,                /* type# */
MD_COL_LEN NUMBER,
MD_COL_PREC NUMBER,                /* precision */
MD_COL_SCALE NUMBER,
MD_COL_CHARSETID NUMBER,           /* character set id */
MD_COL_CHARSETFORM NUMBER,         /* character set form */
MD_COL_ALT_TYPE VARCHAR2(4000),    /* adt type if any */
MD_COL_ALT_PREC NUMBER,            /* precision of the adt attribute */
MD_COL_ALT_CHAR_USED VARCHAR2(2),  /* charset used by the adt attribute */
MD_COL_ALT_LENGTH NUMBER,          /* length of the adt attribute */
MD_COL_ALT_XML_TYPE NUMBER,        /* 0/1. is xml_type column */
MD_COL_ALT_BINARYXML_TYPE NUMBER,  /* 0/1. is xml_type stored as binary */
MD_COL_ENC_ISENC VARCHAR2(3) ,     /* 'YES'/'NO' */
MD_COL_ENC_NOSALT VARCHAR2(3) ,    /* 'YES'/'NO' */
MD_COL_ENC_ISLOB VARCHAR2(3) ,     /* 'YES'/'NO' */
MD_COL_ALT_OBJECTXML_TYPE NUMBER,  /* 0/1 xml_type stored as object */
MD_COL_HASNOTNULLDEFAULT VARCHAR2(3) ,   /* 'YES'/'NO' */
MD_COL_ALT_TYPE_OWNER VARCHAR2(384),  /* owner of the adt type if any */
PROPERTY NUMBER,
XCOLTYPEFLAGS NUMBER,
XOPQTYPEFLAGS NUMBER,
EAFLAGS NUMBER,
XFQCOLNAME VARCHAR2(4000),
SPARE1  NUMBER,
SPARE2  NUMBER,
SPARE3  NUMBER,
SPARE4  VARCHAR2(4000),
SPARE5  VARCHAR2(4000),
SPARE6  VARCHAR2(4000),
/* Following fields added in 12.1.0.2 */
OBJV# NUMBER,
INTCOL# NUMBER,
INTERVAL_LEADING_PRECISION NUMBER,
INTERVAL_TRAILING_PRECISION NUMBER,
TOID RAW(16),
TYPENAME VARCHAR2(384),
NUMINTCOLS NUMBER,
NUMATTRS NUMBER,
ADTORDER NUMBER,
LOGMNR_SPARE1 NUMBER,
LOGMNR_SPARE2 NUMBER,
LOGMNR_SPARE3 VARCHAR2(1000),
LOGMNR_SPARE4 DATE,
LOGMNR_SPARE5 NUMBER,
LOGMNR_SPARE6 NUMBER,
LOGMNR_SPARE7 NUMBER,
LOGMNR_SPARE8 NUMBER,
LOGMNR_SPARE9 NUMBER,
XTYPENAME VARCHAR2(4000),
XTOPINTCOL NUMBER,
XREFFEDTABLEOBJN NUMBER,
XREFFEDTABLEOBJV NUMBER,
XOPQTYPETYPE NUMBER,
XOPQLOBINTCOL NUMBER,
XOPQOBJINTCOL NUMBER,
XXMLINTCOL    NUMBER,
LOGMNRDERIVEDFLAGS NUMBER,
/* Following fields added in 12.2 */
COLLID      NUMBER,
COLLINTCOL#  NUMBER,
ACDRRESCOL# NUMBER
);

/
--------------------------------------------------------
--  DDL for Type LOGMNR$COL_GG_RECS
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TYPE "SYSTEM"."LOGMNR$COL_GG_RECS" AS TABLE OF  SYSTEM.LOGMNR$COL_GG_REC;

/
--------------------------------------------------------
--  DDL for Type LOGMNR$GSBA_GG_REC
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TYPE "SYSTEM"."LOGMNR$GSBA_GG_REC" AS OBJECT
(
LOGMNR_UID NUMBER,
NAME           VARCHAR2(384),
VALUE          VARCHAR2(4000),
LOGMNR_SPARE1  NUMBER,
LOGMNR_SPARE2  NUMBER,
LOGMNR_SPARE3  VARCHAR2(4000),
LOGMNR_SPARE4  DATE
);

/
--------------------------------------------------------
--  DDL for Type LOGMNR$GSBA_GG_RECS
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TYPE "SYSTEM"."LOGMNR$GSBA_GG_RECS" AS TABLE OF  SYSTEM.LOGMNR$GSBA_GG_REC;

/
--------------------------------------------------------
--  DDL for Type LOGMNR$KEY_GG_REC
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TYPE "SYSTEM"."LOGMNR$KEY_GG_REC" as object
(
LOGMNR_UID NUMBER,
KEY# NUMBER,                   /* index obj# or con# */
KEY_FLAGS NUMBER,              /* index or constraint */
KEY_NAME VARCHAR2(384),        /* index name or constraint name */
INDEX_OWNER# NUMBER,
INDEX_OWNERNAME VARCHAR2(384),
COLNAME VARCHAR2(384),
INTCOL# NUMBER,
which number,
KEY_ORDER VARCHAR2(10),              /* asc or desc */
KEYCOL_FLAGS NUMBER,           /* Column properties such as is_null */
SPARE1  NUMBER,
SPARE2  NUMBER,
SPARE3  NUMBER,
SPARE4  VARCHAR2(4000),
SPARE5  VARCHAR2(4000),
SPARE6  VARCHAR2(4000)
);

/
--------------------------------------------------------
--  DDL for Type LOGMNR$KEY_GG_RECS
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TYPE "SYSTEM"."LOGMNR$KEY_GG_RECS" AS TABLE OF  SYSTEM.LOGMNR$KEY_GG_REC;

/
--------------------------------------------------------
--  DDL for Type LOGMNR$SEQ_GG_REC
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TYPE "SYSTEM"."LOGMNR$SEQ_GG_REC" as object
(
LOGMNR_UID NUMBER,
OBJ# NUMBER,
NAME VARCHAR2(384),
OWNER# NUMBER,
OWNERNAME VARCHAR2(384),
FLAGS NUMBER,
MD_TAB_SEQCACHE NUMBER,
MD_TAB_SEQINCREMENTBY NUMBER,
SPARE1  NUMBER,
SPARE2  NUMBER,
SPARE3  NUMBER,
SPARE4  VARCHAR2(4000),
SPARE5  VARCHAR2(4000),
SPARE6  VARCHAR2(4000)
);

/
--------------------------------------------------------
--  DDL for Type LOGMNR$SEQ_GG_RECS
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TYPE "SYSTEM"."LOGMNR$SEQ_GG_RECS" AS TABLE OF  SYSTEM.LOGMNR$SEQ_GG_REC;

/
--------------------------------------------------------
--  DDL for Type LOGMNR$TAB_GG_REC
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TYPE "SYSTEM"."LOGMNR$TAB_GG_REC" as object
(
LOGMNR_UID NUMBER,
OBJ# NUMBER,
BASEOBJV# NUMBER,
MD_TAB_USERID NUMBER,                /* owner# */
MD_TAB_COLCOUNT NUMBER,              /* user column count */
MD_TAB_TOTAL_COL_NUM NUMBER,         /* kernal column count */
MD_TAB_LOG_GROUP_EXISTS NUMBER,      /* Any log group exists for this table */
MD_TAB_IOT VARCHAR2(3) ,             /* 'YES'/'NO' IS IOT? */
MD_TAB_IOT_OVERFLOW VARCHAR2(3) ,    /* 'YES'/'NO' IOT with overflow ? */
MD_TAB_PARTITION  VARCHAR2(3) ,      /* 'YES'/'NO' is partitioned ? */
MD_TAB_SUBPARTITION VARCHAR2(3) ,    /* 'YES'/'NO' is sub partitioned? */
MD_TAB_XMLTYPETABLE VARCHAR2(3) ,    /* 'YES'/'NO' is xmltype table? */
MD_TAB_OBJECTID NUMBER,              /* object id if table object */
MD_TAB_OWNER VARCHAR2(384),     /* owner name */
MD_TAB_NAME VARCHAR2(384),      /* table name */
MD_TAB_OBJTYPE VARCHAR2(384),   /* Object type name */
MD_TAB_SCN NUMBER,                   /* COMMIT_SCN of this table version */
TAB_FLAGS NUMBER,
TRIGFLAG NUMBER,
OBJ_FLAGS NUMBER,
PROPERTY NUMBER,
PARTTYPE NUMBER,
SUBPARTTYPE NUMBER,
SPARE1  NUMBER,
SPARE2  NUMBER,
SPARE3  NUMBER,
SPARE4  VARCHAR2(4000),
SPARE5  VARCHAR2(4000),
SPARE6  VARCHAR2(4000),
/* Following fields added in 12.1.0.2 */
LVLCNT NUMBER,
LVL1OBJ# NUMBER,
LVL2OBJ# NUMBER,
LVL1TYPE# NUMBER,
LVL2TYPE# NUMBER,
LVL1NAME  VARCHAR2(384),
LVL2NAME  VARCHAR2(384),
INTCOLS   NUMBER,
ASSOC#    NUMBER,
XIDUSN    NUMBER,
XIDSLT    NUMBER,
XIDSQN    NUMBER,
DROP_SCN  NUMBER,
FLAGS     NUMBER,
LOGMNR_SPARE1   NUMBER,
LOGMNR_SPARE2   NUMBER,
LOGMNR_SPARE3   VARCHAR2(1000),
LOGMNR_SPARE4   DATE,
LOGMNR_SPARE5   NUMBER,
LOGMNR_SPARE6   NUMBER,
LOGMNR_SPARE7   NUMBER,
LOGMNR_SPARE8   NUMBER,
LOGMNR_SPARE9   NUMBER,
UNSUPPORTEDCOLS  NUMBER,
COMPLEXTYPECOLS  NUMBER,
NTPARENTOBJNUM   NUMBER,
NTPARENTOBJVERSION NUMBER,
NTPARENTINTCOLNUM  NUMBER,
LOGMNRTLOFLAGS    NUMBER,
LOGMNRMCV VARCHAR2(30),
/* Following fields added in 12.2 */
ACDRFLAGS        NUMBER,                                    /* automatic CDR */
ACDRTSOBJ#       NUMBER,                                    /* automatic CDR */
ACDRROWTSINTCOL# NUMBER                                     /* automatic CDR */
);

/
--------------------------------------------------------
--  DDL for Type LOGMNR$TAB_GG_RECS
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TYPE "SYSTEM"."LOGMNR$TAB_GG_RECS" AS TABLE OF  SYSTEM.LOGMNR$TAB_GG_REC;

/
--------------------------------------------------------
--  DDL for Table GZCRM_CERTIFICATE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GZCRM_CERTIFICATE" 
   (	"CM_KEY" VARCHAR2(255 BYTE), 
	"CM_ID" CHAR(6 BYTE), 
	"CM_CERTIFICATE_NAME" VARCHAR2(50 BYTE), 
	"CM_CERTIFICATE_TYPE" VARCHAR2(10 BYTE), 
	"CM_CERTIFICATE_NO" VARCHAR2(20 BYTE), 
	"CM_CERTIFICATE_UNIT" VARCHAR2(50 BYTE), 
	"CM_START_DATE" VARCHAR2(20 BYTE), 
	"CM_END_DATE" VARCHAR2(20 BYTE), 
	"CM_PERIOD" NUMBER(*,0), 
	"CM_CERTIFICATE_URL" VARCHAR2(255 BYTE), 
	"CM_INVALID" VARCHAR2(100 BYTE), 
	"CM_REMARK" VARCHAR2(255 BYTE), 
	"CM_MODIFICATION_DATE" VARCHAR2(255 BYTE), 
	"CM_MODIFICATION_PERSON" VARCHAR2(36 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GZCRM_CINFO
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GZCRM_CINFO" 
   (	"C_KEY" NUMBER(*,0), 
	"C_CM_ID" NUMBER(*,0), 
	"C_SSN" VARCHAR2(18 BYTE), 
	"C_NAME" VARCHAR2(8 BYTE), 
	"C_TEL" VARCHAR2(26 BYTE), 
	"C_SALARY" NUMBER(12,2), 
	"C_BALANCE" NUMBER(12,2), 
	"C_DEBT" NUMBER(12,2), 
	"C_BUSINESS" VARCHAR2(255 BYTE), 
	"C_UNIT" VARCHAR2(100 BYTE), 
	"C_ADD" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GZCRM_CMARKETING_RECORD
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GZCRM_CMARKETING_RECORD" 
   (	"C_KEY" VARCHAR2(255 BYTE), 
	"C_CM_ID" CHAR(6 BYTE), 
	"C_NAME" VARCHAR2(9 BYTE), 
	"C_MANAGEMENT" VARCHAR2(255 BYTE), 
	"C_DEMAND" VARCHAR2(255 BYTE), 
	"C_REPORT" VARCHAR2(255 BYTE), 
	"C_TESTIMONLALS" VARCHAR2(255 BYTE), 
	"C_EVALUATION" VARCHAR2(255 BYTE), 
	"C_DATE" VARCHAR2(255 BYTE), 
	"C_ID" VARCHAR2(36 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GZCRM_CMASS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GZCRM_CMASS" 
   (	"CM_KEY" VARCHAR2(255 BYTE), 
	"CM_ID" CHAR(6 BYTE), 
	"CM_ASSTIME" VARCHAR2(20 BYTE), 
	"CM_ASSUB" VARCHAR2(100 BYTE), 
	"CM_ASSPERIOD" VARCHAR2(50 BYTE), 
	"CM_ASSRESULT" VARCHAR2(10 BYTE), 
	"CM_APPRAISAL" VARCHAR2(10 BYTE), 
	"CM_ASSUNIT" VARCHAR2(50 BYTE), 
	"CM_REMARK" VARCHAR2(255 BYTE), 
	"CM_ATTACHMENT" VARCHAR2(255 BYTE), 
	"CM_MODIFICATION_PERSON" VARCHAR2(36 BYTE), 
	"CM_MODIFICATION_DATE" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GZCRM_CMINFO
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GZCRM_CMINFO" 
   (	"CM_ID" NUMBER(*,0), 
	"CM_NAME" VARCHAR2(9 BYTE), 
	"CM_SEX" VARCHAR2(2 BYTE), 
	"CM_SSN" VARCHAR2(18 BYTE), 
	"CM_BIRTHDAY" VARCHAR2(20 BYTE), 
	"CM_AGE" NUMBER(*,0), 
	"CM_NATION" VARCHAR2(30 BYTE), 
	"CM_POLITICAL_LANDSCAPE" VARCHAR2(20 BYTE), 
	"CM_HOMETOWN" VARCHAR2(255 BYTE), 
	"CM_PHOTO" VARCHAR2(255 BYTE), 
	"CM_EDUCATION" VARCHAR2(10 BYTE), 
	"CM_DEGREE" VARCHAR2(20 BYTE), 
	"CM_STATUS" VARCHAR2(4 BYTE), 
	"CM_GRADUATED" VARCHAR2(100 BYTE), 
	"CM_PROFESSIONAL_TITLES" VARCHAR2(50 BYTE), 
	"CM_HIREDATE" VARCHAR2(20 BYTE), 
	"CM_ENTRY_TIME" VARCHAR2(20 BYTE), 
	"CM_FINANCIAL_YEARS" NUMBER(*,0), 
	"CM_WORKING_YEARS" NUMBER(*,0), 
	"CM_EXIT_TIME" DATE, 
	"CM_RESULTS_LAST_YEAR" NUMBER(*,0), 
	"CM_YEAR_CREDITS" NUMBER(*,0), 
	"CM_TOTAL_CREDITS" NUMBER(*,0), 
	"CM_LEVEL" VARCHAR2(5 BYTE), 
	"CM_UNIT" VARCHAR2(50 BYTE), 
	"CM_DEPT" VARCHAR2(20 BYTE), 
	"CM_POSITION" VARCHAR2(20 BYTE), 
	"CM_TEL" VARCHAR2(13 BYTE), 
	"CM_MOBILE" VARCHAR2(11 BYTE), 
	"CM_BUSINESS_LINES" VARCHAR2(10 BYTE), 
	"CM_CERTIFICATE_NUMBER" VARCHAR2(20 BYTE), 
	"CM_QUALIFICATION_DATE" VARCHAR2(20 BYTE), 
	"CM_QUALIFICATION_PERIOD" NUMBER(*,0), 
	"CM_STATUS_NUMBER" VARCHAR2(20 BYTE), 
	"CM_STATUS_NUMBER_DATE" VARCHAR2(20 BYTE), 
	"CM_STATUS_NUMBER_PERIOD" NUMBER(*,0), 
	"CM_LEVEL_NUMBER" VARCHAR2(20 BYTE), 
	"CM_LEVEL_DATE" VARCHAR2(20 BYTE), 
	"CM_LEVEL_PERIOD" NUMBER(*,0), 
	"CM_MODIFICATION_DATE" VARCHAR2(20 BYTE), 
	"CM_MODIFICATION_PERSON" VARCHAR2(36 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GZCRM_CMINFO_WORK
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GZCRM_CMINFO_WORK" 
   (	"CM_KEY" VARCHAR2(255 BYTE), 
	"CM_ID" CHAR(6 BYTE), 
	"CM_MANAGEMENT" VARCHAR2(255 BYTE), 
	"CM_PRODUCT" VARCHAR2(255 BYTE), 
	"CM_LOAN" VARCHAR2(255 BYTE), 
	"CM_WARNING" VARCHAR2(255 BYTE), 
	"CM_ISSUE" VARCHAR2(255 BYTE), 
	"CM_WORK_PROPOSAL" LONG, 
	"CM_DATE" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GZCRM_CMLEVEL
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GZCRM_CMLEVEL" 
   (	"CM_KEY" VARCHAR2(255 BYTE), 
	"CM_ID" CHAR(6 BYTE), 
	"CM_HOLD_DATE" VARCHAR2(255 BYTE), 
	"CM_HOLD_LEVEL" VARCHAR2(20 BYTE), 
	"CM_HOLD_TPYE" VARCHAR2(10 BYTE), 
	"CM_ATTACHMENT" VARCHAR2(255 BYTE), 
	"CM_MODIFICATION_PERSON" VARCHAR2(36 BYTE), 
	"CM_MODIFICATION_DATE" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GZCRM_CMLTR
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GZCRM_CMLTR" 
   (	"CM_KEY" VARCHAR2(255 BYTE), 
	"CM_ID" CHAR(6 BYTE), 
	"CM_TDATE" VARCHAR2(20 BYTE), 
	"CM_SUB" VARCHAR2(50 BYTE), 
	"CM_TUNIT" VARCHAR2(50 BYTE), 
	"CM_STARTDATE" VARCHAR2(20 BYTE), 
	"CM_ENDDATE" VARCHAR2(20 BYTE), 
	"CM_KNOW" VARCHAR2(255 BYTE), 
	"CM_CREDIT" NUMBER(*,0), 
	"CM_SCORE" NUMBER(3,2), 
	"CM_ATTACHMENT" VARCHAR2(255 BYTE), 
	"CM_REMARK" VARCHAR2(255 BYTE), 
	"CM_MODIFICATION_PERSON" VARCHAR2(255 BYTE), 
	"CM_MODIFICATION_DATE" VARCHAR2(36 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GZCRM_CMREGULAR
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GZCRM_CMREGULAR" 
   (	"CM_KEY" VARCHAR2(10 BYTE), 
	"CM_ID" VARCHAR2(10 BYTE), 
	"CM_REGULAR_DATE" VARCHAR2(50 BYTE), 
	"CM_REGULAR_PERSONNEL" VARCHAR2(50 BYTE), 
	"CM_REGULAR_THEME" VARCHAR2(50 BYTE), 
	"CM_ATTACHMENT" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GZCRM_CMRESULTS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GZCRM_CMRESULTS" 
   (	"CM_KEY" VARCHAR2(255 BYTE), 
	"CM_ID" CHAR(6 BYTE), 
	"CM_YEAR" VARCHAR2(15 BYTE), 
	"CM_RESULT" VARCHAR2(255 BYTE), 
	"CM_ATTACHMENT" VARCHAR2(255 BYTE), 
	"CM_MODIFICATION_DATE" VARCHAR2(255 BYTE), 
	"CM_MODIFICATION_PERSON" VARCHAR2(36 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GZCRM_CMRPR
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GZCRM_CMRPR" 
   (	"CM_KEY" VARCHAR2(255 BYTE), 
	"CM_ID" CHAR(6 BYTE), 
	"CM_TPYE" VARCHAR2(10 BYTE), 
	"CM_SUB" VARCHAR2(255 BYTE), 
	"CM_DATE" VARCHAR2(20 BYTE), 
	"CM_AUNIT" VARCHAR2(50 BYTE), 
	"CM_APERSON" VARCHAR2(9 BYTE), 
	"CM_RDATE" VARCHAR2(255 BYTE), 
	"CM_AREASON" VARCHAR2(100 BYTE), 
	"CM_REMARK" VARCHAR2(255 BYTE), 
	"CM_ATTACHMENT" VARCHAR2(255 BYTE), 
	"CM_MODIFICATION_DATE" VARCHAR2(20 BYTE), 
	"CM_MODIFICATION_PERSON" VARCHAR2(36 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GZCRM_CMWORK
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GZCRM_CMWORK" 
   (	"CM_KEY" VARCHAR2(255 BYTE), 
	"CM_ID" CHAR(6 BYTE), 
	"CM_OFFICE_DATE" VARCHAR2(20 BYTE), 
	"CM_POSITION" VARCHAR2(20 BYTE), 
	"CM_UNIT" VARCHAR2(50 BYTE), 
	"CM_ATTACHMENT" VARCHAR2(255 BYTE), 
	"CM_WORK" LONG, 
	"CM_MODIFICATION_DATE" VARCHAR2(255 BYTE), 
	"CM_MODIFICATION_PERSON" VARCHAR2(36 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GZCRM_LEARN
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GZCRM_LEARN" 
   (	"L_KEY" VARCHAR2(255 BYTE), 
	"L_NAME" VARCHAR2(255 BYTE), 
	"L_TYPE" VARCHAR2(20 BYTE), 
	"L_DES" VARCHAR2(255 BYTE), 
	"L_URL" VARCHAR2(255 BYTE), 
	"L_LINE" VARCHAR2(10 BYTE), 
	"L_UPER" VARCHAR2(36 BYTE), 
	"L_UNIT" VARCHAR2(50 BYTE), 
	"L_DATE" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table YC_MEMBER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."YC_MEMBER" 
   (	"MEM_ID" NUMBER(*,0), 
	"CNAME" VARCHAR2(50 BYTE), 
	"MEM_PASS" VARCHAR2(400 BYTE), 
	"MEM_SEX" VARCHAR2(4 BYTE), 
	"MEM_BORN" VARCHAR2(50 BYTE), 
	"MEM_MAIL" VARCHAR2(50 BYTE), 
	"MEM_QUESTION" VARCHAR2(50 BYTE), 
	"MEM_ANSWER" VARCHAR2(50 BYTE), 
	"REGISTER_TIME" VARCHAR2(50 BYTE), 
	"LAST_TIME" VARCHAR2(50 BYTE), 
	"ISENABLE" VARCHAR2(1 BYTE), 
	"ROLEID" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table YC_PARAMS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."YC_PARAMS" 
   (	"PARAMTYPE" VARCHAR2(20 BYTE), 
	"PARAMCODE" VARCHAR2(20 BYTE), 
	"PARAMNAME" VARCHAR2(100 BYTE), 
	"PARAMTYPENAME" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID
--------------------------------------------------------

   CREATE SEQUENCE  "SYSTEM"."SEQ_ID"  MINVALUE 1 MAXVALUE 99999999999999999 INCREMENT BY 1 START WITH 400 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_IDD
--------------------------------------------------------

   CREATE SEQUENCE  "SYSTEM"."SEQ_IDD"  MINVALUE 1 MAXVALUE 99999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_IDDD
--------------------------------------------------------

   CREATE SEQUENCE  "SYSTEM"."SEQ_IDDD"  MINVALUE 1 MAXVALUE 99999999999999999 INCREMENT BY 1 START WITH 25 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
REM INSERTING into SYSTEM.GZCRM_CERTIFICATE
SET DEFINE OFF;
Insert into SYSTEM.GZCRM_CERTIFICATE (CM_KEY,CM_ID,CM_CERTIFICATE_NAME,CM_CERTIFICATE_TYPE,CM_CERTIFICATE_NO,CM_CERTIFICATE_UNIT,CM_START_DATE,CM_END_DATE,CM_PERIOD,CM_CERTIFICATE_URL,CM_INVALID,CM_REMARK,CM_MODIFICATION_DATE,CM_MODIFICATION_PERSON) values ('383','466   ','DA',null,'45','DWA',null,null,1,null,null,null,'2021-06-16','admin');
REM INSERTING into SYSTEM.GZCRM_CINFO
SET DEFINE OFF;
Insert into SYSTEM.GZCRM_CINFO (C_KEY,C_CM_ID,C_SSN,C_NAME,C_TEL,C_SALARY,C_BALANCE,C_DEBT,C_BUSINESS,C_UNIT,C_ADD) values (1,1,'372323191121210213','test1','13721138901',3000,700,300.32,'基金定投','致远贸易','济南');
Insert into SYSTEM.GZCRM_CINFO (C_KEY,C_CM_ID,C_SSN,C_NAME,C_TEL,C_SALARY,C_BALANCE,C_DEBT,C_BUSINESS,C_UNIT,C_ADD) values (2,2,'372323191121210232','test2','13621138901',4000,700,300.32,'基金定投','致远贸易','济南');
Insert into SYSTEM.GZCRM_CINFO (C_KEY,C_CM_ID,C_SSN,C_NAME,C_TEL,C_SALARY,C_BALANCE,C_DEBT,C_BUSINESS,C_UNIT,C_ADD) values (3,1,'372323191121210213','test3','13821138901',3000,700,300.32,'基金定投','致远贸易','济南');
Insert into SYSTEM.GZCRM_CINFO (C_KEY,C_CM_ID,C_SSN,C_NAME,C_TEL,C_SALARY,C_BALANCE,C_DEBT,C_BUSINESS,C_UNIT,C_ADD) values (4,2,'372323191121210232','test4','13121138901',4000,700,300.32,'基金定投','致远贸易','济南');
Insert into SYSTEM.GZCRM_CINFO (C_KEY,C_CM_ID,C_SSN,C_NAME,C_TEL,C_SALARY,C_BALANCE,C_DEBT,C_BUSINESS,C_UNIT,C_ADD) values (5,1,'372323191121210213','test5','13221138901',3000,700,300.32,'基金定投','致远贸易','济南');
Insert into SYSTEM.GZCRM_CINFO (C_KEY,C_CM_ID,C_SSN,C_NAME,C_TEL,C_SALARY,C_BALANCE,C_DEBT,C_BUSINESS,C_UNIT,C_ADD) values (6,2,'372323191121210232','test6','13321138901',4000,700,300.32,'基金定投','致远贸易','北京');
Insert into SYSTEM.GZCRM_CINFO (C_KEY,C_CM_ID,C_SSN,C_NAME,C_TEL,C_SALARY,C_BALANCE,C_DEBT,C_BUSINESS,C_UNIT,C_ADD) values (7,1,'372323191121210213','test7','13421138901',3000,700,300.32,'基金定投','致远贸易','北京');
Insert into SYSTEM.GZCRM_CINFO (C_KEY,C_CM_ID,C_SSN,C_NAME,C_TEL,C_SALARY,C_BALANCE,C_DEBT,C_BUSINESS,C_UNIT,C_ADD) values (8,2,'372323191121210232','test8','13521138901',4000,700,300.32,'基金定投','致远贸易','北京');
Insert into SYSTEM.GZCRM_CINFO (C_KEY,C_CM_ID,C_SSN,C_NAME,C_TEL,C_SALARY,C_BALANCE,C_DEBT,C_BUSINESS,C_UNIT,C_ADD) values (9,1,'372323191121210213','test9','13621138901',3000,700,300.32,'基金定投','致远贸易','北京');
Insert into SYSTEM.GZCRM_CINFO (C_KEY,C_CM_ID,C_SSN,C_NAME,C_TEL,C_SALARY,C_BALANCE,C_DEBT,C_BUSINESS,C_UNIT,C_ADD) values (10,2,'372323191121210232','test10','15721138901',4000,700,300.32,'基金定投','致远贸易','上海');
Insert into SYSTEM.GZCRM_CINFO (C_KEY,C_CM_ID,C_SSN,C_NAME,C_TEL,C_SALARY,C_BALANCE,C_DEBT,C_BUSINESS,C_UNIT,C_ADD) values (11,1,'372323191121210213','test11','18721138901',3000,700,300.32,'基金定投','致远贸易','上海');
Insert into SYSTEM.GZCRM_CINFO (C_KEY,C_CM_ID,C_SSN,C_NAME,C_TEL,C_SALARY,C_BALANCE,C_DEBT,C_BUSINESS,C_UNIT,C_ADD) values (12,2,'372323191121210232','test12','18721138901',4000,700,300.32,'基金定投','致远贸易','上海');
Insert into SYSTEM.GZCRM_CINFO (C_KEY,C_CM_ID,C_SSN,C_NAME,C_TEL,C_SALARY,C_BALANCE,C_DEBT,C_BUSINESS,C_UNIT,C_ADD) values (13,2,'372323191121210232','test13','18721138901',4000,700,300.32,'基金定投','致远贸易','南京');
Insert into SYSTEM.GZCRM_CINFO (C_KEY,C_CM_ID,C_SSN,C_NAME,C_TEL,C_SALARY,C_BALANCE,C_DEBT,C_BUSINESS,C_UNIT,C_ADD) values (14,2,'372323191121210232','test14','18721138901',4000,700,300.32,'基金定投','致远贸易','南京');
Insert into SYSTEM.GZCRM_CINFO (C_KEY,C_CM_ID,C_SSN,C_NAME,C_TEL,C_SALARY,C_BALANCE,C_DEBT,C_BUSINESS,C_UNIT,C_ADD) values (15,2,'372323191121210232','test15','18721138901',4000,700,300.32,'基金定投','致远贸易','南京');
REM INSERTING into SYSTEM.GZCRM_CMARKETING_RECORD
SET DEFINE OFF;
Insert into SYSTEM.GZCRM_CMARKETING_RECORD (C_KEY,C_CM_ID,C_NAME,C_MANAGEMENT,C_DEMAND,C_REPORT,C_TESTIMONLALS,C_EVALUATION,C_DATE,C_ID) values ('2','1     ','test2','dsa','sa',null,null,null,'dwa','2');
Insert into SYSTEM.GZCRM_CMARKETING_RECORD (C_KEY,C_CM_ID,C_NAME,C_MANAGEMENT,C_DEMAND,C_REPORT,C_TESTIMONLALS,C_EVALUATION,C_DATE,C_ID) values ('1','1     ','test1','dsa','sa',null,null,null,'2545','1');
REM INSERTING into SYSTEM.GZCRM_CMASS
SET DEFINE OFF;
Insert into SYSTEM.GZCRM_CMASS (CM_KEY,CM_ID,CM_ASSTIME,CM_ASSUB,CM_ASSPERIOD,CM_ASSRESULT,CM_APPRAISAL,CM_ASSUNIT,CM_REMARK,CM_ATTACHMENT,CM_MODIFICATION_PERSON,CM_MODIFICATION_DATE) values ('382','466   ','2012',null,null,null,null,null,null,null,'admin','2021-06-16');
REM INSERTING into SYSTEM.GZCRM_CMINFO
SET DEFINE OFF;
Insert into SYSTEM.GZCRM_CMINFO (CM_ID,CM_NAME,CM_SEX,CM_SSN,CM_BIRTHDAY,CM_AGE,CM_NATION,CM_POLITICAL_LANDSCAPE,CM_HOMETOWN,CM_PHOTO,CM_EDUCATION,CM_DEGREE,CM_STATUS,CM_GRADUATED,CM_PROFESSIONAL_TITLES,CM_HIREDATE,CM_ENTRY_TIME,CM_FINANCIAL_YEARS,CM_WORKING_YEARS,CM_EXIT_TIME,CM_RESULTS_LAST_YEAR,CM_YEAR_CREDITS,CM_TOTAL_CREDITS,CM_LEVEL,CM_UNIT,CM_DEPT,CM_POSITION,CM_TEL,CM_MOBILE,CM_BUSINESS_LINES,CM_CERTIFICATE_NUMBER,CM_QUALIFICATION_DATE,CM_QUALIFICATION_PERIOD,CM_STATUS_NUMBER,CM_STATUS_NUMBER_DATE,CM_STATUS_NUMBER_PERIOD,CM_LEVEL_NUMBER,CM_LEVEL_DATE,CM_LEVEL_PERIOD,CM_MODIFICATION_DATE,CM_MODIFICATION_PERSON) values (466,'1','M','1','02-2月 -20',1,'01','1','灞变笢娴庡崡',null,'1','1','0','1','01','09-9月 -20','09-9月 -20',1,1,null,null,null,null,'0','1','1','1','1','1','1',null,null,null,null,null,null,null,null,null,'2021-06-16',null);
REM INSERTING into SYSTEM.GZCRM_CMINFO_WORK
SET DEFINE OFF;
Insert into SYSTEM.GZCRM_CMINFO_WORK (CM_KEY,CM_ID,CM_MANAGEMENT,CM_PRODUCT,CM_LOAN,CM_WARNING,CM_ISSUE,CM_WORK_PROPOSAL,CM_DATE) values ('1','1     ','dsa',null,null,null,null,null,'45');
REM INSERTING into SYSTEM.GZCRM_CMLEVEL
SET DEFINE OFF;
Insert into SYSTEM.GZCRM_CMLEVEL (CM_KEY,CM_ID,CM_HOLD_DATE,CM_HOLD_LEVEL,CM_HOLD_TPYE,CM_ATTACHMENT,CM_MODIFICATION_PERSON,CM_MODIFICATION_DATE) values ('361','1     ','23','34','3',null,'admin','2021-06-16');
REM INSERTING into SYSTEM.GZCRM_CMLTR
SET DEFINE OFF;
Insert into SYSTEM.GZCRM_CMLTR (CM_KEY,CM_ID,CM_TDATE,CM_SUB,CM_TUNIT,CM_STARTDATE,CM_ENDDATE,CM_KNOW,CM_CREDIT,CM_SCORE,CM_ATTACHMENT,CM_REMARK,CM_MODIFICATION_PERSON,CM_MODIFICATION_DATE) values ('377','466   ',null,null,null,null,null,null,null,null,null,null,null,'2021-06-16');
REM INSERTING into SYSTEM.GZCRM_CMREGULAR
SET DEFINE OFF;
Insert into SYSTEM.GZCRM_CMREGULAR (CM_KEY,CM_ID,CM_REGULAR_DATE,CM_REGULAR_PERSONNEL,CM_REGULAR_THEME,CM_ATTACHMENT) values ('362','362','ea','dsa','1',null);
REM INSERTING into SYSTEM.GZCRM_CMRESULTS
SET DEFINE OFF;
REM INSERTING into SYSTEM.GZCRM_CMRPR
SET DEFINE OFF;
Insert into SYSTEM.GZCRM_CMRPR (CM_KEY,CM_ID,CM_TPYE,CM_SUB,CM_DATE,CM_AUNIT,CM_APERSON,CM_RDATE,CM_AREASON,CM_REMARK,CM_ATTACHMENT,CM_MODIFICATION_DATE,CM_MODIFICATION_PERSON) values ('381','466   ',null,null,null,null,null,null,null,null,null,'2021-06-16',null);
REM INSERTING into SYSTEM.GZCRM_CMWORK
SET DEFINE OFF;
Insert into SYSTEM.GZCRM_CMWORK (CM_KEY,CM_ID,CM_OFFICE_DATE,CM_POSITION,CM_UNIT,CM_ATTACHMENT,CM_WORK,CM_MODIFICATION_DATE,CM_MODIFICATION_PERSON) values ('1','1     ',null,null,null,null,null,null,null);
Insert into SYSTEM.GZCRM_CMWORK (CM_KEY,CM_ID,CM_OFFICE_DATE,CM_POSITION,CM_UNIT,CM_ATTACHMENT,CM_WORK,CM_MODIFICATION_DATE,CM_MODIFICATION_PERSON) values ('4','3     ','3','3','3',null,'3','2021-06-16','admin');
Insert into SYSTEM.GZCRM_CMWORK (CM_KEY,CM_ID,CM_OFFICE_DATE,CM_POSITION,CM_UNIT,CM_ATTACHMENT,CM_WORK,CM_MODIFICATION_DATE,CM_MODIFICATION_PERSON) values ('21','466   ',null,null,null,null,null,'2021-06-16','admin');
REM INSERTING into SYSTEM.GZCRM_LEARN
SET DEFINE OFF;
Insert into SYSTEM.GZCRM_LEARN (L_KEY,L_NAME,L_TYPE,L_DES,L_URL,L_LINE,L_UPER,L_UNIT,L_DATE) values ('0','dsad','学习培训材料','dsada',null,'T','admin','银行','2021-06-16');
Insert into SYSTEM.GZCRM_LEARN (L_KEY,L_NAME,L_TYPE,L_DES,L_URL,L_LINE,L_UPER,L_UNIT,L_DATE) values ('340','DSAD','规章制度','EWQEWQ',null,null,'admin','银行','2021-06-16');
REM INSERTING into SYSTEM.YC_MEMBER
SET DEFINE OFF;
Insert into SYSTEM.YC_MEMBER (MEM_ID,CNAME,MEM_PASS,MEM_SEX,MEM_BORN,MEM_MAIL,MEM_QUESTION,MEM_ANSWER,REGISTER_TIME,LAST_TIME,ISENABLE,ROLEID) values (1,'admin','1','F','1980-01-01','212121212@qq.com','myqq','212121212','2016-01-01','2021-06-16','T','1');
Insert into SYSTEM.YC_MEMBER (MEM_ID,CNAME,MEM_PASS,MEM_SEX,MEM_BORN,MEM_MAIL,MEM_QUESTION,MEM_ANSWER,REGISTER_TIME,LAST_TIME,ISENABLE,ROLEID) values (2,'Tom','1','M','1983-01-01','212121213@qq.com','myqq','212121212','2016-01-01','2016-11-02','T','1');
Insert into SYSTEM.YC_MEMBER (MEM_ID,CNAME,MEM_PASS,MEM_SEX,MEM_BORN,MEM_MAIL,MEM_QUESTION,MEM_ANSWER,REGISTER_TIME,LAST_TIME,ISENABLE,ROLEID) values (3,'Lily','1','M','1982-01-01','212121214@qq.com','myqq','212121212','2016-01-01','2016-11-03','T','2');
Insert into SYSTEM.YC_MEMBER (MEM_ID,CNAME,MEM_PASS,MEM_SEX,MEM_BORN,MEM_MAIL,MEM_QUESTION,MEM_ANSWER,REGISTER_TIME,LAST_TIME,ISENABLE,ROLEID) values (4,'zhangsan','1','F','1981-01-01','212121215@qq.com','myqq','212121212','2016-01-01','2016-11-04','T','2');
Insert into SYSTEM.YC_MEMBER (MEM_ID,CNAME,MEM_PASS,MEM_SEX,MEM_BORN,MEM_MAIL,MEM_QUESTION,MEM_ANSWER,REGISTER_TIME,LAST_TIME,ISENABLE,ROLEID) values (5,'lisi','1','M','1989-01-01','212121216@qq.com','myqq','212121212','2016-01-01','2016-11-05','T','2');
Insert into SYSTEM.YC_MEMBER (MEM_ID,CNAME,MEM_PASS,MEM_SEX,MEM_BORN,MEM_MAIL,MEM_QUESTION,MEM_ANSWER,REGISTER_TIME,LAST_TIME,ISENABLE,ROLEID) values (6,'wangwu','1','M','1980-01-01','212121217@qq.com','myqq','212121212','2016-01-01','2016-11-06','T','2');
Insert into SYSTEM.YC_MEMBER (MEM_ID,CNAME,MEM_PASS,MEM_SEX,MEM_BORN,MEM_MAIL,MEM_QUESTION,MEM_ANSWER,REGISTER_TIME,LAST_TIME,ISENABLE,ROLEID) values (343,'aSd','666666',null,null,'1111@qq.con','6位吉祥数字','666666','2021-06-16','2021-06-16','F','2');
Insert into SYSTEM.YC_MEMBER (MEM_ID,CNAME,MEM_PASS,MEM_SEX,MEM_BORN,MEM_MAIL,MEM_QUESTION,MEM_ANSWER,REGISTER_TIME,LAST_TIME,ISENABLE,ROLEID) values (363,'xiaolu','666666','F','2021-06-05','22222@qq.com','myqq','22222','2021-06-16','2021-06-16','T','2');
Insert into SYSTEM.YC_MEMBER (MEM_ID,CNAME,MEM_PASS,MEM_SEX,MEM_BORN,MEM_MAIL,MEM_QUESTION,MEM_ANSWER,REGISTER_TIME,LAST_TIME,ISENABLE,ROLEID) values (364,'1d','666666','M','31','1111@qq.con','6位吉祥数字','666666','2021-06-16','2021-06-16','F','2');
Insert into SYSTEM.YC_MEMBER (MEM_ID,CNAME,MEM_PASS,MEM_SEX,MEM_BORN,MEM_MAIL,MEM_QUESTION,MEM_ANSWER,REGISTER_TIME,LAST_TIME,ISENABLE,ROLEID) values (365,'xiaolu','666666','F','2021-06-05','22222@qq.com','myqq','22222','2021-06-16','2021-06-16','T','2');
Insert into SYSTEM.YC_MEMBER (MEM_ID,CNAME,MEM_PASS,MEM_SEX,MEM_BORN,MEM_MAIL,MEM_QUESTION,MEM_ANSWER,REGISTER_TIME,LAST_TIME,ISENABLE,ROLEID) values (366,'xiaolu','666666','F','2021-06-05','22222@qq.com','myqq','22222','2021-06-16','2021-06-16','T','2');
Insert into SYSTEM.YC_MEMBER (MEM_ID,CNAME,MEM_PASS,MEM_SEX,MEM_BORN,MEM_MAIL,MEM_QUESTION,MEM_ANSWER,REGISTER_TIME,LAST_TIME,ISENABLE,ROLEID) values (367,'xiaolu','666666','F','2021-06-05','22222@qq.com','myqq','22222','2021-06-16','2021-06-16','T','2');
Insert into SYSTEM.YC_MEMBER (MEM_ID,CNAME,MEM_PASS,MEM_SEX,MEM_BORN,MEM_MAIL,MEM_QUESTION,MEM_ANSWER,REGISTER_TIME,LAST_TIME,ISENABLE,ROLEID) values (368,'xiaolu','666666','F','2021-06-05','22222@qq.com','myqq','22222','2021-06-16','2021-06-16','T','2');
Insert into SYSTEM.YC_MEMBER (MEM_ID,CNAME,MEM_PASS,MEM_SEX,MEM_BORN,MEM_MAIL,MEM_QUESTION,MEM_ANSWER,REGISTER_TIME,LAST_TIME,ISENABLE,ROLEID) values (369,'xiaolu','666666','F','2021-06-05','22222@qq.com','myqq','22222','2021-06-16','2021-06-16','T','2');
Insert into SYSTEM.YC_MEMBER (MEM_ID,CNAME,MEM_PASS,MEM_SEX,MEM_BORN,MEM_MAIL,MEM_QUESTION,MEM_ANSWER,REGISTER_TIME,LAST_TIME,ISENABLE,ROLEID) values (370,'xiaolu','666666','F','2021-06-05','22222@qq.com','myqq','22222','2021-06-16','2021-06-16','T','2');
REM INSERTING into SYSTEM.YC_PARAMS
SET DEFINE OFF;
Insert into SYSTEM.YC_PARAMS (PARAMTYPE,PARAMCODE,PARAMNAME,PARAMTYPENAME) values ('05','01','初级客户经理','客户经理等级');
Insert into SYSTEM.YC_PARAMS (PARAMTYPE,PARAMCODE,PARAMNAME,PARAMTYPENAME) values ('05','02','中级客户经理','客户经理等级');
Insert into SYSTEM.YC_PARAMS (PARAMTYPE,PARAMCODE,PARAMNAME,PARAMTYPENAME) values ('05','03','高级客户经理','客户经理等级');
Insert into SYSTEM.YC_PARAMS (PARAMTYPE,PARAMCODE,PARAMNAME,PARAMTYPENAME) values ('01','1','中共党员','政治面貌');
Insert into SYSTEM.YC_PARAMS (PARAMTYPE,PARAMCODE,PARAMNAME,PARAMTYPENAME) values ('01','2','群众','政治面貌');
Insert into SYSTEM.YC_PARAMS (PARAMTYPE,PARAMCODE,PARAMNAME,PARAMTYPENAME) values ('01','3','中共团员','政治面貌');
Insert into SYSTEM.YC_PARAMS (PARAMTYPE,PARAMCODE,PARAMNAME,PARAMTYPENAME) values ('02','01','汉族','民族');
Insert into SYSTEM.YC_PARAMS (PARAMTYPE,PARAMCODE,PARAMNAME,PARAMTYPENAME) values ('02','02','维吾尔族','民族');
Insert into SYSTEM.YC_PARAMS (PARAMTYPE,PARAMCODE,PARAMNAME,PARAMTYPENAME) values ('02','03','朝鲜族','民族');
Insert into SYSTEM.YC_PARAMS (PARAMTYPE,PARAMCODE,PARAMNAME,PARAMTYPENAME) values ('02','04','傣族','民族');
Insert into SYSTEM.YC_PARAMS (PARAMTYPE,PARAMCODE,PARAMNAME,PARAMTYPENAME) values ('02','05','壮族','民族');
Insert into SYSTEM.YC_PARAMS (PARAMTYPE,PARAMCODE,PARAMNAME,PARAMTYPENAME) values ('02','06','满族','民族');
Insert into SYSTEM.YC_PARAMS (PARAMTYPE,PARAMCODE,PARAMNAME,PARAMTYPENAME) values ('02','07','苗族','民族');
Insert into SYSTEM.YC_PARAMS (PARAMTYPE,PARAMCODE,PARAMNAME,PARAMTYPENAME) values ('03','1','小学','学历');
Insert into SYSTEM.YC_PARAMS (PARAMTYPE,PARAMCODE,PARAMNAME,PARAMTYPENAME) values ('03','2','初中','学历');
Insert into SYSTEM.YC_PARAMS (PARAMTYPE,PARAMCODE,PARAMNAME,PARAMTYPENAME) values ('03','3','高中','学历');
Insert into SYSTEM.YC_PARAMS (PARAMTYPE,PARAMCODE,PARAMNAME,PARAMTYPENAME) values ('03','4','大学本科','学历');
Insert into SYSTEM.YC_PARAMS (PARAMTYPE,PARAMCODE,PARAMNAME,PARAMTYPENAME) values ('03','5','研究生','学历');
Insert into SYSTEM.YC_PARAMS (PARAMTYPE,PARAMCODE,PARAMNAME,PARAMTYPENAME) values ('04','1','小学','学位');
Insert into SYSTEM.YC_PARAMS (PARAMTYPE,PARAMCODE,PARAMNAME,PARAMTYPENAME) values ('04','2','初中','学位');
Insert into SYSTEM.YC_PARAMS (PARAMTYPE,PARAMCODE,PARAMNAME,PARAMTYPENAME) values ('04','3','高中','学位');
Insert into SYSTEM.YC_PARAMS (PARAMTYPE,PARAMCODE,PARAMNAME,PARAMTYPENAME) values ('04','4','学士','学位');
Insert into SYSTEM.YC_PARAMS (PARAMTYPE,PARAMCODE,PARAMNAME,PARAMTYPENAME) values ('04','5','硕士','学位');
--------------------------------------------------------
--  DDL for Index SYS_C007877
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007877" ON "SYSTEM"."GZCRM_CERTIFICATE" ("CM_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007857
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007857" ON "SYSTEM"."GZCRM_CMARKETING_RECORD" ("C_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007873
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007873" ON "SYSTEM"."GZCRM_CMASS" ("CM_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007855
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007855" ON "SYSTEM"."GZCRM_CMINFO" ("CM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007863
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007863" ON "SYSTEM"."GZCRM_CMINFO_WORK" ("CM_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007869
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007869" ON "SYSTEM"."GZCRM_CMLEVEL" ("CM_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007871
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007871" ON "SYSTEM"."GZCRM_CMLTR" ("CM_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007853
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007853" ON "SYSTEM"."GZCRM_CMREGULAR" ("CM_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007867
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007867" ON "SYSTEM"."GZCRM_CMRESULTS" ("CM_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007875
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007875" ON "SYSTEM"."GZCRM_CMRPR" ("CM_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007865
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007865" ON "SYSTEM"."GZCRM_CMWORK" ("CM_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007861
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007861" ON "SYSTEM"."GZCRM_LEARN" ("L_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_ID" ON "SYSTEM"."YC_MEMBER" ("MEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Function LOGMNR$COL_GG_TABF_PUBLIC
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE FUNCTION "SYSTEM"."LOGMNR$COL_GG_TABF_PUBLIC" wrapped
a000000
1
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
8
237 185
nkvJV1w6wH1y7mRApzf9mGuebNUwgxDILkhGfHQCmP8+Vi4fyqh3SG1Fyq+pCts1OlgnK761
YuzKBA4JE5DNwZzBIF/Y4ZM5eUlquVyTkOg+AodK3vQJt9NLvPITXbP42O37gO+zKr4BQEJk
ypwrP1U/Pf6MLZONN8LUaVqHCN87T14HqHs5taX7LhLXQ2lCVBE1Ll8dyB9CDOlbyvQS/lrb
+0n1pQi9IJAWySL85ChAqnTaqFJm0YeToD4lZ8UUPQqIZNoX0x73WK9OzsmdBrvEC97iduxe
PEXVkxF6xklPod6yOGBvW7DAFMBgf+LajDLVKOAwB2EAiKCXYMuTUTtMYYkCFFf4sj1rCpsj
TLth6TSru530aM2HP6bEbm3m

/
--------------------------------------------------------
--  DDL for Function LOGMNR$GSBA_GG_TABF_PUBLIC
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE FUNCTION "SYSTEM"."LOGMNR$GSBA_GG_TABF_PUBLIC" wrapped
a000000
1
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
8
204 16d
TJgbwETdggmXz74u7w/JrOCMLZUwgwLIr0hGfHSiEv/qVCcobaDmzQ1NW9NZS4lXFtygg175
tZarVC/jhB662Fj0ml9YLlHdj6yBdiTYfbxUuglkxmUXzYWprDJI/x819+U/W/+HCzSEVTo4
eyQupUEJ82oFYTEdyuCX9zVB8VDEnCzvqzdYyfXbV6b0CW2Ewgo4dfm4MlwRwDYuaMYXqNwR
fxX+KM+f8oxs4qwnmjQByrcYKddGnKCC7kqfOEW7VrXXUkLrYhQhQThaJ63/NezIPczX5qxx
7sY9gkBTrPNqH6DNPg4qqMfl0x8VNJCg9Vt/eo+ffUg9GSESima5hw28P14yBe1z4RIYP0Y=


/
--------------------------------------------------------
--  DDL for Function LOGMNR$KEY_GG_TABF_PUBLIC
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE FUNCTION "SYSTEM"."LOGMNR$KEY_GG_TABF_PUBLIC" wrapped
a000000
1
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
8
2a0 1a1
3O4I5hDO715d8A2tqbxMCflFW0owg/D319xqfC9Grfg+K6yE71zMvtNS45AyRXBk77WpI5v4
nUSfE2lbvUYgk3JHySIe28XxC3xIYYpPGQjxwa3GzPw0FN5aN6kerQQTHUBp29Dd+vLSgBaC
2pAFrq059ZvN0ZPN11XG/2RuDY7HaTQu/QffhnY8rVlNxpFmbkVidwtZQahx5qIFu9Uww/tv
o1AvhjaORi898/KiPtOqv7LpsPFbyNuMnZEG48cxtZuesMBJFP/bKtgU2DN69xiT8Pxf+N2n
g0D2ximYzZqwY/4dBQj9dyQDuXRFo40hdqtWw0L96zV6723aQ8Xp0cqBaZj2wWTI4+6Ikry9
zY0Mdm3bV8TYqsOa+zT4fnikGO0eYbTFHEiW9QUbl/UwzuERwk8p

/
--------------------------------------------------------
--  DDL for Function LOGMNR$SEQ_GG_TABF_PUBLIC
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE FUNCTION "SYSTEM"."LOGMNR$SEQ_GG_TABF_PUBLIC" wrapped
a000000
1
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
8
249 181
++dDv/cHZatK7/vHG9lvR8DQCpYwg/D3AEhqfHQC2h6ONoOvOeHvTNX1S5GDyajM4j8vkSVz
IMw+LbYS3goujprvmrB/LUpdBF8TVvjEqZpC7MCKPXWcGnTeL7ja8C2tcOdjOpRXkwL5NmPJ
B0KqMvwepdiQDY7HUDQrBddQC1lBqHGEogWkwRJ3+2+jUC+Gpo5GTazIWS0V551NkSl3+h0W
BhkPglLbvQDPzxWTnmu4ZuJIlTiNwTf1R0WxghyyKFjES9CJsCrGT8Fn7prlF4Mr5kx1YBGf
5xaODtRnmVJgb65RlKbAN9+Xxf2QnQjKQL99RZAgsEwGVKNfx9lFKwHLGUwzjOxmIAXXYd/Z
+L9osPQJjZYkNrD0pQ==

/
--------------------------------------------------------
--  DDL for Function LOGMNR$TAB_GG_TABF_PUBLIC
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE FUNCTION "SYSTEM"."LOGMNR$TAB_GG_TABF_PUBLIC" wrapped
a000000
1
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
8
22e 181
PRVt0FiLRPgjIhZlCZcQhnOHXQ4wgzJp2UhGfHSKrQ843hKm3gKD9swoFAS4jVcW0CsSl7W1
6banVWdjktOVM18XyRjY4ZM5eRdquSp0ZdfHl3KJPBYqPi9LXIwum30Qh7ymgO+zTKj+R1N2
nSs/TPnknfYLwcUdAfBryDQGEIMisMuE9XT5ix3sudhHa5tLJRjsBIDKlqL7zk2CH0C1NRAZ
XrP7WgavVdNS3Yikz88VupZG21hTuAGspJBgCagmNWIwi9pgCIWP3rxF4p+uMps/ABEg+MBP
6Iykm62kO6hWhVHJXkfKF/jrQFjYBTTzatr1VTcOXt/AFuagDR7isNtb//lnXh8TXyAFWyCT
ubv6GXL0aM0PP/t+DfSl

/
--------------------------------------------------------
--  DDL for Synonymn CATALOG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE SYNONYM "SYSTEM"."CATALOG" FOR "SYS"."CATALOG";
--------------------------------------------------------
--  DDL for Synonymn COL
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE SYNONYM "SYSTEM"."COL" FOR "SYS"."COL";
--------------------------------------------------------
--  DDL for Synonymn PRODUCT_USER_PROFILE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE SYNONYM "SYSTEM"."PRODUCT_USER_PROFILE" FOR "SYSTEM"."SQLPLUS_PRODUCT_PROFILE";
--------------------------------------------------------
--  DDL for Synonymn PUBLICSYN
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE SYNONYM "SYSTEM"."PUBLICSYN" FOR "SYS"."PUBLICSYN";
--------------------------------------------------------
--  DDL for Synonymn SYSCATALOG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE SYNONYM "SYSTEM"."SYSCATALOG" FOR "SYS"."SYSCATALOG";
--------------------------------------------------------
--  DDL for Synonymn SYSFILES
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE SYNONYM "SYSTEM"."SYSFILES" FOR "SYS"."SYSFILES";
--------------------------------------------------------
--  DDL for Synonymn TAB
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE SYNONYM "SYSTEM"."TAB" FOR "SYS"."TAB";
--------------------------------------------------------
--  DDL for Synonymn TABQUOTAS
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE SYNONYM "SYSTEM"."TABQUOTAS" FOR "SYS"."TABQUOTAS";
--------------------------------------------------------
--  Constraints for Table GZCRM_CERTIFICATE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GZCRM_CERTIFICATE" MODIFY ("CM_KEY" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GZCRM_CERTIFICATE" ADD PRIMARY KEY ("CM_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GZCRM_CMARKETING_RECORD
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GZCRM_CMARKETING_RECORD" MODIFY ("C_KEY" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GZCRM_CMARKETING_RECORD" ADD PRIMARY KEY ("C_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GZCRM_CMASS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GZCRM_CMASS" MODIFY ("CM_KEY" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GZCRM_CMASS" ADD PRIMARY KEY ("CM_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GZCRM_CMINFO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GZCRM_CMINFO" MODIFY ("CM_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GZCRM_CMINFO" ADD PRIMARY KEY ("CM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GZCRM_CMINFO_WORK
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GZCRM_CMINFO_WORK" MODIFY ("CM_KEY" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GZCRM_CMINFO_WORK" ADD PRIMARY KEY ("CM_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GZCRM_CMLEVEL
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GZCRM_CMLEVEL" MODIFY ("CM_KEY" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GZCRM_CMLEVEL" ADD PRIMARY KEY ("CM_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GZCRM_CMLTR
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GZCRM_CMLTR" MODIFY ("CM_KEY" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GZCRM_CMLTR" ADD PRIMARY KEY ("CM_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GZCRM_CMREGULAR
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GZCRM_CMREGULAR" ADD PRIMARY KEY ("CM_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GZCRM_CMRESULTS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GZCRM_CMRESULTS" MODIFY ("CM_KEY" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GZCRM_CMRESULTS" ADD PRIMARY KEY ("CM_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GZCRM_CMRPR
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GZCRM_CMRPR" MODIFY ("CM_KEY" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GZCRM_CMRPR" ADD PRIMARY KEY ("CM_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GZCRM_CMWORK
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GZCRM_CMWORK" MODIFY ("CM_KEY" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GZCRM_CMWORK" ADD PRIMARY KEY ("CM_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GZCRM_LEARN
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GZCRM_LEARN" MODIFY ("L_KEY" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GZCRM_LEARN" ADD PRIMARY KEY ("L_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table YC_MEMBER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."YC_MEMBER" MODIFY ("MEM_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."YC_MEMBER" ADD CONSTRAINT "PK_ID" PRIMARY KEY ("MEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GZCRM_CINFO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GZCRM_CINFO" ADD CONSTRAINT "FK_GID" FOREIGN KEY ("C_CM_ID")
	  REFERENCES "SYSTEM"."YC_MEMBER" ("MEM_ID") ENABLE;
